source 'https://rubygems.org'
ruby "2.3.1"

gem 'bundler', '>= 1.8.4'
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.6'
# A simple, versatile notification library
gem 'rails-assets-notifyjs', source: 'https://rails-assets.org'
# Translations for the kaminari gem
gem 'kaminari-i18n', '~> 0.3.2'
# A Scope & Engine based, clean, powerful, customizable and sophisticated paginator for Ruby webapps
gem 'kaminari'
# Internationalization (i18n) library for Ruby http://rails-i18n.org/wiki
gem 'rails-i18n', '~> 4.0.0'
# A library for generating fake data such as names, addresses, and phone numbers
gem 'faker'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# O Lero-lero Generator é uma ferramenta capaz de gerar frases que 'falam' muita coisa mas que não tem conteúdo algum.
gem 'lerolero_generator'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Dynamic nested forms using jQuery made easy; works with formtastic, simple_form or default forms
gem "cocoon"
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# The most popular front-end framework for developing responsive, mobile first projects on the web.
gem 'rails-assets-bootstrap', '3.3.6', source: 'https://rails-assets.org'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
  # Rails >= 3 pry initializer
  gem 'pry-rails'
  # Use sqlite3 as the database for Active Record
  gem 'sqlite3'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

group :production do
	# Heroku dependency
	gem 'pg'
	# Heroku dependency
	gem 'rails_12factor'
end

